data:
    aem_folder: 'aem_data'
    train_data:
        aem_train_data:
            - 'high_res_cond_clip_albers_skip_6.shp'
        targets:
            - 'interpretation_zone53_albers_study_area_Ceno_depth.shp'
        weights:
            - 1
    apply_model: 'high_res_cond_clip_albers_skip_6.shp'
    weight_col: 'BoundConf'
    line_col: 'SURVEY_LIN'
    conductivity_columns_prefix: 'cond'
    thickness_columns_prefix: 'thick'
    aem_covariate_cols:
        - 'ceno_euc_a'
        - 'Gravity_la'
        - 'national_W'
        - 'relief_ele'
        - 'relief_mrv'
        - 'SagaWET9ce'
        - 'elevation'
        - 'tx_height'
    # aem line scan radius in meters - aem points are assumed to be on the same flight line under this radius
    aem_line_scan_radius: 500
    # aem lines are split into batches of aem_line_splits's to generate artificial splits
    aem_line_splits: 1000
    test_train_split:
        train: 0.6
        val: 0.2
        test: 0.2
    rows: -1

learning:
    algorithm: gradientboost
    params:
        loss: 'ls'
        max_depth: 10
        learning_rate: 0.1
        n_estimators: 10
        subsample: 0.8
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.05
        max_features: "auto"
        alpha: 0.95
    weighted_model:
        weights:
            H: 2
            M: 1
            L: 0.5
    cross_validation:
        kfold: 5
    numpy_seed: 10
    include_aem_covariates: true
    include_thickness: true
    include_conductivity_derivatives: true
    smooth_twod_covariates: true
    smooth_covariates_kernel_size: (21, 3)
    optimisation:
        searchcv_params:
            n_iter: 60
            cv: 2
            verbose: 1000
            n_points: 10
            n_jobs: 20
        params_space:
            'max_depth': Integer(1, 15)
            'learning_rate': Real(10 ** -5, 10 ** 0, prior="log-uniform")
            'n_estimators': Integer(10, 100)
            'subsample': Real(0.01, 1.0, prior='uniform')
            'max_features': Categorical(['auto', 'sqrt', 'log2'])
            'min_samples_split': Integer(2, 50)
            'min_samples_leaf': Integer(1, 50)
            'min_weight_fraction_leaf': Real(0.0, 0.5, prior='uniform')

output:
    directory: out
    train:
        covariates_csv: true
        true_vs_pred: true
    pred:
        quantiles: 0.95
        optimised_model: true
        covariates_csv: true
        pred: true
