data:
    aem_folder: 'aem_data'
    train_data:
        aem_train_data:
            - 'train.shp'
        targets:
            - 'interpretation_zone53_albers_study_area_Ceno_depth.shp'
        weights:
            - 1
    apply_model:
        - 'oos.shp'
    weight_col: 'BoundConf'
    target_col: 'DEPTH'
    target_type_col: 'Type'  # Type
    included_target_type_categories:
        - 'BASE_Cenozoic_TOP_Mesozoic'
#        - 'BASE_Cenozoic_TOP_Neoproterozoic'
#        - 'BASE_Cenozoic_TOP_Paleozoic'
#        - 'BASE_Cenozoic_TOP_Pre-Neoproterozoic'
    line_col: 'SURVEY_LIN'
    conductivity_columns_prefix: 'cond'
    thickness_columns_prefix: 'thick'
    group_col: cluster_line_segment_id   # optional, `cluster_line_segment_id` is determined by clustering algo
    # if a different group_col is provided via the shapefile that is used instead
    cutoff_radius: 500
    aem_covariate_cols:
        - 'ceno_euc_a'
        - 'Gravity_la'
        - 'national_W'
        - 'relief_ele'
        - 'relief_mrv'
        - 'SagaWET9ce'
        - 'elevation'
        - 'tx_height'
    # aem line scan radius in meters - aem points are assumed to be on the same flight line under this radius
    aem_line_scan_radius: 500
    # aem lines are split into batches of aem_line_splits's to generate artificial splits
    aem_line_splits: 1000
    test_train_split:  # currently unused
        train: 0.6
        val: 0.2
        test: 0.2
    rows: -1
    oos_validation:
        aem_validation_data:
            - 'oos.shp'
        targets:
            - 'interpretation_zone53_albers_study_area_Ceno_depth.shp'

learning:
    algorithm: quantilegb
    params:
        max_depth: 20
        upper_alpha: 90
        lower_alpha: 10
        learning_rate: 0.1
        n_estimators: 200
        subsample: 0.9
        min_samples_split: 2
        min_samples_leaf: 2
        min_weight_fraction_leaf: 0.0
        max_features: "auto"
        random_state: 3
    cross_validation:
        kfold: 3
    weighted_model:
        weights_map:
            H: 2
            M: 1
            L: 0.5
    numpy_seed: 10
    include_aem_covariates: true
    include_thickness: true
    include_conductivity_derivatives: true
    smooth_twod_covariates: true
    smooth_covariates_kernel_size: (21, 3)

output:
    directory: out/quantile_gb/
    train:
        covariates_csv: true
        true_vs_pred: true
    pred:
        quantiles: 0.95
        optimised_model: true
        covariates_csv: true
        pred: true
