name: aem-ml CI


on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - '**'

jobs:
  build:
    if: ${{ ! (contains(github.event.head_commit.message, 'ci skip') || contains(github.event.head_commit.message, 'skip ci'))}}
    runs-on: ubuntu-18.04
    name: Python ${{ matrix.python }}
    strategy:
      matrix:
        include:
          - build: 1
            python-version: "3.7"

    env:
      PIP_WHEEL_DIR: "/home/runner/.cache/pip/wheels"
      PIP_FIND_LINKS: "file:///home/runner/.cache/pip/wheels"
      PYTHONVERSION: ${{ matrix.python-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Cache multiple paths
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/gdalinstall
          key: ${{ runner.os }}-cache-GDAL-${{ matrix.GDALVERSION }}-proj-${{ matrix.PROJVERSION }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Common set up ${{ matrix.python-version }}
        run: |
          sudo apt update
          sudo apt upgrade
          python -m pip install -U pip wheel
      - name: Install packages
        run: sudo apt install libhdf5-serial-dev libnetcdf13 libatlas-base-dev gfortran
      - name: Python ${{ matrix.python-version }}
        run: |
          pip install -r requirements.txt -r requirements_dev.txt
          python setup.py install
          rm -rf aem.egg-info  # remove the local egg
          echo "PYTHONPATH=$(pwd):$PYTHONPATH" >> $GITHUB_ENV
      - name: Test aem-ml in Python ${{ matrix.python-version }}
        run: |
          pytest tests/
